sapegin/mrm

Readme.md

Change references of `taks` to `tasks` (unless that is intentional then just close this).

docs(README): Fix spelling mistake [skip ci].

---

Readme.md
bin/mrm.js
package-lock.json
package.json
src/__mocks__/directories.js
src/__tests__/index.spec.js
src/errors.js
src/index.js
src/tasks/codecov/index.js
src/tasks/license/index.js
src/tasks/package/index.js
src/tasks/readme/index.js
src/tasks/stylelint/index.js
src/tasks/travis/index.js

- Do not require config file.
- Validate each config option separately.
- Throw only if options is not difined and no default value provided.
- Allow overriding config options via command line.
Todo:

Rewrite configuration management

---

bin/mrm.js

There is no guarantee the `_` variable is available in the shell. At least in PowerShell it isn't, and it was throwing errors at me. Otherwise mrm seems to work fine on Windows.
There is still a minor downside though: in case the var doesn't exist, the printed binary name will always be `mrm` even when used via npx.

Guard against absence of the "_" env var

---

docs/Writing_tasks.md
packages/mrm-core/src/index.js
packages/mrm/package-lock.json
packages/mrm/src/__tests__/index.spec.js
packages/mrm/src/index.js
packages/mrm/test/dir3/task6/index.js
packages/mrm/test/dir5/task8/index.js

Tasks now receive an object with resolved values (merged config, command line and interactive values). Defaults, validations and interactive prompts are defined via `parameters` object. See docs for more details.
`values()`, `require()` and `defaults()` methods on config object are deprecated and will be removed in the next major release.

feat: Finish interactive mode

---

packages/mrm/bin/mrm.js
packages/mrm/src/__tests__/index.spec.js
packages/mrm/src/index.js

Closes #75
| Before the changes | After the changes |
| - | - | 
| ![image](https://user-images.githubusercontent.com/48519/80160801-cef2d780-85ce-11ea-8623-fb257d04c4ac.png) | ![image](https://user-images.githubusercontent.com/48519/80160587-483dfa80-85ce-11ea-8929-43ca09611039.png) |
The idea was to make sure packages like `@myorg/default` would try to be resolved as both `@myorg/mrm-preset-default` and `@myorg/default`, so even if you pass `@myorg/mrm-preset-default` it will still resolve.
There are no breaking changes introduced, all tests are passing.
I wasn't sure about the `package-lock.json` files, so I didn't commit them since I didn't change anhy of the dependencies.
Let me know if anything needs to be changed.
Cheers

feat: resolve scoped presets and tasks

---

packages/mrm-core/types/index.d.ts

Json's `.set()` can be called with one or two parameters, but the current `mrm-core` types do not reflect this.
This PR updates the `Json` type interface to include this usage pattern.

Add missing set function signature for JSON to mrm-core types

---

packages/mrm-core/Readme.md
packages/mrm-core/package-lock.json
packages/mrm-core/package.json
packages/mrm-core/src/__tests__/npm.spec.js
packages/mrm-core/src/npm.js

This change addresses #89 
- Fixes handling of non-registry packages by omitting version information by default.
- When a non-registry package is given an explicit version, uses the `#semver:<semver>` syntax, as supported by NPM and Yarn (https://docs.npmjs.com/cli/install)
- Adds tests for the above.

fix: Handle non-registry installs

---

packages/mrm/bin/mrm.js
packages/mrm/package-lock.json
packages/mrm/package.json
packages/mrm/src/__tests__/index.spec.js
packages/mrm/src/index.js

This is just a PoC for now, definitely could be better built out. This will try to install a preset or task package globally if it is found on NPM (including namespaced packages), Prompting the user first if this is desired.
Rel: https://github.com/sapegin/mrm/issues/59

feat: automatic global install for tasks and presets

---

packages/mrm-task-license/__snapshots__/index.spec.js.snap
packages/mrm-task-license/index.js
packages/mrm-task-license/index.spec.js

Hi!
Base on npm documentation: https://docs.npmjs.com/files/package.json#people-fields-author-contributors, author field can be an object on an string. In this PR try to add this behavior to mrm task license

update mrm-task-license — add new entry for author name

---

packages/mrm-task-eslint/Readme.md
packages/mrm-task-eslint/__snapshots__/index.spec.js.snap
packages/mrm-task-eslint/index.js
packages/mrm-task-eslint/index.spec.js

This change expands the set of eslint preset names accepted by the eslint task to be closer to [what is accepted by eslint for the `extends` configuration option](https://eslint.org/docs/developer-guide/shareable-configs) including scoped packages and intra-package configs (e.g. `eslint-config-airbnb/whitespace`). This change does not include support for presets specified by a file path.
It's worth noting that the [`@eslint/eslintrc`](https://github.com/eslint/eslintrc) package exports a `normalizePackageName` function, but there are a couple issues with that:
1. The package is explicitly marked as not for external use
2. The function does not handle intra-package configs

Accept more types of eslint presets

---

packages/mrm-core/src/__tests__/npm.spec.js
packages/mrm-core/src/npm.js

This fixes the issue of running any tasks that install additional packages while working in a yarn workspace. This will always add the flag [--ignore-workspace-root-check](https://classic.yarnpkg.com/en/docs/cli/add/#toc-yarn-add-ignore-workspace-root-check-w) to the `yarn add` commands. Adding this flag when yarn is not using workspaces will cause no effect, and does not break anything.
This likely resolves the issue in #48.

fix(mrm-core): Fix adding packages to yarn workspaces

---

docs/Making_presets.md

In my view, it dilutes the `mrm-task` category if adding presets into it. Better, imo, to use `mrm` if looking for a category that is generic to both tasks and presets.

Removing mrm-task as keyword

---

packages/mrm-task-license/Readme.md
packages/mrm-task-license/index.js
packages/mrm-task-license/index.spec.js
packages/mrm-task-license/package.json
packages/mrm-task-readme/Readme.md
packages/mrm-task-readme/__snapshots__/index.spec.js.snap
packages/mrm-task-readme/index.js
packages/mrm-task-readme/index.spec.js
packages/mrm-task-readme/package.json

This allows `licenseFile` to be template-based with a dynamic `${license}` portion, and adds the same to the `readme` task for parity. Will only be used if user uses template with `${license}`. Allow for preserving a file name style, e.g., `LICENSE-MIT.md` without hard-coding the license in, and allowing the license to more easily be swapped out so as to impact the name also.
And as with #123, let me know if you want `smpltmpl` reexported from mrm-core.

feat(license): file name template-based

---

packages/mrm-core/src/npm.js
packages/mrm-task-license/package-lock.json
packages/mrm-task-readme/Readme.md
packages/mrm-task-readme/__snapshots__/index.spec.js.snap
packages/mrm-task-readme/index.js
packages/mrm-task-readme/index.spec.js
packages/mrm-task-readme/package-lock.json
packages/mrm-task-readme/templates/Contributing.md
packages/mrm-task-readme/templates/Readme.md

I didn't know if you might want `smpltmpl` exposed from `mrm-core`, so added as a direct dependency for now (also whether you'd like a `cross-spawn` utility in core as I think might be useful to expose).
Thanks!

feat(readme): Make contributing conditional by `includeContributing` option and allow `contributingFile` option for name

---

packages/mrm/package-lock.json
packages/mrm/package.json

First step in deprecating the default preset as mentioned in #135.
I think actual deprecation must be performed with an `npm` command. We can remove the default preset from packages but I'm not sure if it should wait or be performed here as well.

Remove default preset from mrm package deps

---

packages/mrm-task-lint-staged/index.js
packages/mrm-task-lint-staged/index.spec.js

Longer-term, mrm should look at offering the option and being compatible with both 4/5, but for now, pinning @ 4 prevents the lint-staged action from being broken.
See https://github.com/sapegin/mrm/issues/145
Tested locally using `npm link`.

Fix broken lint-staged action by explicitly pining Husky to 4.x

---

package-lock.json
packages/mrm-core/package-lock.json
packages/mrm-core/package.json
packages/mrm-core/src/index.js
packages/mrm-core/src/npm.js
packages/mrm-preset-default/package-lock.json
packages/mrm-task-ci/package-lock.json
packages/mrm-task-codecov/package-lock.json
packages/mrm-task-contributing/package-lock.json
packages/mrm-task-dependabot/package-lock.json
packages/mrm-task-editorconfig/package-lock.json
packages/mrm-task-eslint/package-lock.json
packages/mrm-task-gitignore/package-lock.json
packages/mrm-task-gitter/package-lock.json
packages/mrm-task-jest/package-lock.json
packages/mrm-task-license/package-lock.json
packages/mrm-task-lint-staged/package-lock.json
packages/mrm-task-package/__snapshots__/index.spec.js.snap
packages/mrm-task-package/index.js
packages/mrm-task-package/package-lock.json
packages/mrm-task-package/package.json
packages/mrm-task-prettier/package-lock.json
packages/mrm-task-readme/package-lock.json
packages/mrm-task-semantic-release/package-lock.json
packages/mrm-task-styleguidist/package-lock.json
packages/mrm-task-stylelint/package-lock.json
packages/mrm-task-travis/package-lock.json
packages/mrm-task-typescript/package-lock.json
packages/mrm/package-lock.json

Builds on #129.
- feat(package): use any npm init license/version config; add `bugs`, `contributors`; full `repository` URL (easier open-clicking within IDEs)
Those extra `package.json` fields are reported by linters, and `bugs` is used on npmjs.com.
I figure that if you're ok with this, that you might want the npm init in its own package like your `user-meta` package (but since license and version are not quite related to the *user*, I didn't think they'd go there.
I also wasn't sure if there were some way around the need to make a separate mrm-core contribution to expose this API before starting using it (since it will depend on an available version bump), so I added it for now both to core and to the `package` repo.

Task npm init

---

packages/mrm-task-lint-staged/__snapshots__/index.spec.js.snap
packages/mrm-task-lint-staged/index.js
packages/mrm-task-lint-staged/index.spec.js

[`simple-git-hooks`](https://github.com/toplenboren/simple-git-hooks) is a git hook manager.
This migration will bring these benefits to users:
* `simple-git-hooks` has 0 dependencies and took 10 KB of `node_modules` space compared to 1 MB of husky 4.
* `simple-git-hooks` doesn’t read config on every `pre-commit` hook call which increases the performance. It uses the husky 5 model when you need explicitly to call a script on config changes. But it is a good trade-off for `lint-staged` case. It should give around a 0.5 second performance boost for `pre-commit`.
Comparison with husky 5:
1. We can start having all husky 5 benefits (performance, small size) without waiting for MIT license for husky 5.
2. `simple-git-hooks` is smaller than husky 5.
3. husky 5 …

Replace husky 4 to simple-git-hooks

---

site/src/plugins/goatcounter-plugin.js

When the browser fails to load goatcounter (for example, if one blocked by adblocker), clicking on links throws the error:
`Uncaught TypeError: can't access property "count", window.goatcounter is undefined` and prevents any site navigation.

fix(site): Non-clickable links when goatcounter is blocked

---

packages/mrm/bin/mrm.js

Feels like we need a (possibly e2e) regression test but since this is a serious breaking error, fix is our priority.
I tested this locally and it worked.

Remove the require assuming that default preset is installed

---

packages/mrm/bin/mrm.js
packages/mrm/src/__tests__/index.spec.js
packages/mrm/src/index.js

See individual commit messages for details. Fixes #160 (and duplicate #178)

fix: `Cannot read property 'length' of undefined` when listing tasks

---

packages/mrm-core/Readme.md
packages/mrm-core/src/__tests__/npm.spec.js
packages/mrm-core/src/npm.js
packages/mrm-core/types/index.d.ts
packages/mrm-task-gitignore/__snapshots__/index.spec.js.snap
packages/mrm-task-gitignore/index.js
packages/mrm-task-gitignore/index.spec.js
packages/mrm-task-package/index.js
packages/mrm-task-package/index.spec.js

feat(install/uninstall): add pnpm support (option or auto-detect)
This fixes the part of #114 which brings pnpm into parity with existing Yarn/YarnBerry support.

feat(install/uninstall): add pnpm support (option or auto-detect)

---

packages/mrm-core/src/formats/markdown.js

When I ran `npx mrm semantic-release --config:readmeFile=README.md` in my terminal, something unexpected happened
I already had a `README.md` in my project( it's empty though ), but `mrm` still reported
```bash
Can’t add badge: file “README.md” not found.
```
It makes me confused. So I digged into the code a bit
Finally I found the reason( See the `Files changed` part in this PR )

fix: mrm reports file not found although it exists

---

packages/mrm-task-eslint/index.js

The readme in `mrm-task-eslint` says, `eslintPeerDependencies` and `eslintObsoleteDependencies` are optional
```js
require( 'mrm-task-eslint' )( {
eslintPreset: '...',
eslintPeerDependencies: [],
eslintObsoleteDependencies: [],
} )
```
But in fact, if I use `mrm-task-eslint` in the programming way, I must pass an empty array for them, or it will report an error
```bash
TypeError: eslintPeerDependencies/eslintObsoleteDependencies is not iterable
```
We should add default value ( empty array ) for them, not only in `module.exports.parameters`

fix: peer and obsolete deps is not optional

---

packages/mrm-core/src/formats/yaml.js
packages/mrm-core/types/index.d.ts

This is a followup of #113.
In that PR, typescript typing wasn't updated for the yaml function.
And also move the interfaces into module declaration, otherwise these types are not usable by import.

Fix typing of yaml function

---

packages/mrm-core/src/__tests__/npm.spec.js
packages/mrm-core/src/npm.js

Noticed an issue where `runPnpm` was passing `--save` in the args of `uninstall`, causing it to error out due to an unrecognized flag.
Decided to have a look through the pnpm cli docs and update the `runPnpm` args generation.
uninstall -> remove: `uninstall` is an alias for `remove` so might as well just use `remove`
install -> add: `add` is the equivalent of npm's `install` where it installs a package and any packages that it depends on...
--save -> --save-prod: `--save` does not exist as a flag for pnpm `remove`, `--save-dev` and `--save-prod` are documented flags for `add` and `remove`
* https://docs.npmjs.com/cli/v8/commands/npm-install#save
* https://pnpm.io/cli/install
* https://pnpm.io/cli/add
* https://pnpm.io/cli/remove

Update runPnpm install and uninstall

---

package-lock.json
packages/mrm-core/package-lock.json
packages/mrm-preset-default/package-lock.json
packages/mrm-task-ci/package-lock.json
packages/mrm-task-codecov/package-lock.json
packages/mrm-task-contributing/package-lock.json
packages/mrm-task-dependabot/package-lock.json
packages/mrm-task-editorconfig/package-lock.json
packages/mrm-task-eslint/package-lock.json
packages/mrm-task-gitignore/package-lock.json
packages/mrm-task-gitter/package-lock.json
packages/mrm-task-jest/package-lock.json
packages/mrm-task-license/package-lock.json
packages/mrm-task-lint-staged/package-lock.json
packages/mrm-task-package/package-lock.json
packages/mrm-task-prettier/package-lock.json
packages/mrm-task-readme/package-lock.json
packages/mrm-task-semantic-release/package-lock.json
packages/mrm-task-styleguidist/package-lock.json
packages/mrm-task-stylelint/package-lock.json
packages/mrm-task-travis/package-lock.json
packages/mrm-task-typescript/package-lock.json
packages/mrm/package-lock.json

This is a set of "safe" (patch level) across the mono repo.  I think this will silence most of the dependabot issues all at once.  Only package-lock.json files are affected, but in some cases, these are very out-of-date with the old lock file format.

(chore) dependency updates `npx lerna exec npm audit fix`
